packages:
  - examples/fintech-startup
  - packages/create-trousers-app
  - packages/services/trousers-rest-service
  - packages/services/trousers-service-interface
  - packages/trousers-api
  - packages/trousers-data-elasticsearch
  - packages/trousers-data-interfaces
  - packages/trousers-data-postgres
  - packages/trousers-data-sql
  - packages/trousers-domain
