name: Verify

on:
  push:
    branches: [ main ]
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "All's well that ends well, that's what I say."

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm -r build
